displayName=Clan Chat Censor
author=Juhiiis-osrs
description=Replaces messages from players you choose with "Blocked message" and lets you click them to reveal the original.
tags=clan,chat,block,censor,ignore,filter
version=
plugins=com.clanchatcensor.ClanChatCensorPlugin
build=standard